version: "3.9"
services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ui
    ports:
      - "3000:80"
    depends_on:
      - backend
